title: It's all about the life! 
author: Roshan Ghojoghi
email: roshanghojoghi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Roshan Ghojoghi, computer engineering student in Yildiz Technical University based in Istanbul, Turkey.
  My plan is alongside education, I'm gonna learn web and mobile app development in six months.

# social links
twitter_username: PHANTOMxxPAIN # DO NOT include the @ character, or else the build will fail!
github_username:  roshan-gh # DO NOT include the @ character, or else the build will fail!
instagram_username: roshan.gh

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
